### ISSUE TITLE
int21 ah17 FCB rename returns incorrect result when source file missing

### ISSUE THREAD

**Issue by andrewbird** [PerditionC/fdkernel#16]
I think I've found a bug in FreeDOS implementation of int21/17 FCB rename. If the source file does not exist the command still returns success al=0, whereas it should return al=0xff, see RBIL at [int21/17](http://www.ctyme.com/intr/rb-2582.htm) . This was first seen in the Dosemu2 ticket https://github.com/stsp/dosemu2/issues/538, but has also been tested using a simple Qemu hdimage. I've attached the test program and its GNU assembler source. It is hardcoded to look in the current directory for a file called 'testa.bat', it will try to rename that to 'testb.bal' after which it reports whether the rename operation was successful.
[freedos_fcb_rename.zip](https://github.com/PerditionC/fdkernel/files/1499952/freedos_fcb_rename.zip)
Issue seen with FreeDOS 1.0, 1.1 and 1.2

**Comment by stsp** [comment]
Does it set CF?

**Comment by andrewbird** [comment]
I did try altering the code to detect success based on CF whilst testing unded Dosemu and saw no improvement, but I didn't try under qemu. In any case both RBIL and the DOS reference book I have here state that success/fail is determined by checking the value of AL after the call and make no mention of CF indicating failure. That seems to be a common theme through all the FCB based file operations which were in DOS v1 and I suspect that CF checking became the norm from DOS v2 onwards.

**Comment by ecm-pushbx** [comment]
CY on error is used for MS-DOS 2+ functions only. MS-DOS 1 functions, plus all undefined function numbers in ah (eg int 21.71 when no LFN server is present), return only a value in al and leave CF unchanged from the input CF.

**Comment by PerditionC** [comment]
Sorry haven't commented, I will try to look into it this week.   I 've been trying to follow on dosemu thread.

**Comment by andrewbird** [comment]
Sure thing, I'll look forward to it. Is there anything else you need from me to help?
